import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mikan(kari)",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <head>
        <meta name="robots" content="noindex" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100..900&display=swap" rel="stylesheet" />
      </head>
      <body className={inter.className}>
        <header>
          <a href="/" className="header_title">
            <Image src="/logo.png" alt="logo" width={952} height={752} />
            <div>
              <h1>Cleanna Mikan(仮)</h1>
              <p>アントレ用進捗管理サービス</p>
            </div>
          </a>
        </header>
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
