import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mikan(kari)",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <h1>みかん</h1>
          <p>アントレ用進捗管理サービス(仮)</p>
        </header>
        <main>
          {children}
        </main>
        <footer>
          <p>© 2024 asari-web.com</p>
        </footer>
      </body>
    </html>
  );
}
